name: Svelte Website build & push.
run-name: ${{ github.actor }} is building the website.
on:
  push:
    branches:
      - 'svelte-stable'
jobs:
  build:
    name: 'Building the website'
    runs-on: ubuntu-latest
    steps:
      - name: 'Build:checkout'
        uses: actions/checkout@v4
      - name: Set up docker
        uses: papodaca/install-docker-action@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: git.projectsegfau.lt
          username: midou
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v4
        env:
          ACTIONS_RUNTIME_TOKEN: '' # Workaround to some bug specific to gitea actions.
        with:
          tags: git.projectsegfau.lt/midou/midou36o.github.io:latest
          context: '.'
          file: ./Dockerfile
          push: true
